### ISSUE TITLE
Invalid TOKEN in .env

### ISSUE THREAD

**Issue by clydo** [IgorKowalczyk/discord-ssh#218]
Hey!

i'm actually having this error:
@SERVER:~/discord-ssh$ npm run start

> discord-ssh@2.0.1 start
> node index.js

[DISCORD] > Starting SSH...
[ERROR] > Unhandled Rejection: Error: Invalid TOKEN in .env

3 time i've reseted my token, checked synthax and i'm pretty .env is ok. 
Any idea ?

**Comment by IgorKowalczyk** [comment]
Hmm, pretty unusual error, replace these lines in `index.js` https://github.com/IgorKowalczyk/discord-ssh/blob/main/index.js#L132C1-L135C1 with:

```js
client.login(client.config.token).catch((error) => {
 throw new Error(error);
});
```
This code will not fix the error but will display the full error message, then we will know what is wrong
