### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by Remzer59** [IgorKowalczyk/discord-ssh#225]
### Environment

Hello, I've encountered the following error:

root@server:~/discord-ssh# sudo npm run start

> discord-ssh@2.0.1 start
> node index.js

file:///root/discord-ssh/index.js:49
 if (options?.terminal)
             ^

SyntaxError: Unexpected token '.'
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
    
   Running on ubuntu server 22.04, as root
   
   Would you know how to correct that ? 
   
   TIA
  
  Best regards, 

### Steps To Reproduce

Launch the "npm run start" cmd

### Software Version

2.0.1

### Expected Behavior

run the bot

### Actual Behavior

crash

### Severity

Major

### Priority

High

### Type

Functional

### Reproducible

- [X] Yes
- [ ] No

**Comment by IgorKowalczyk** [comment]
Check out https://github.com/IgorKowalczyk/discord-ssh/pull/226 (v3 release soon!)

**Comment by georgetalilo** [comment]
hey! im still having this bug.

**Comment by georgetalilo** [comment]
sorry it was my mistake, i wasn't on the right version of node!
